### PR TITLE
Added Quartus project and settings files for SiDi

### PR DESCRIPTION
**Pull request by alessioscand**

### CODE REVIEW

**Comment by Gehstock** [comment]
This is a Mist Repo, your Push Target should be https://github.com/ManuFerHi/Mist_FPGA

**Comment by gyurco** [comment]
These are source files, and there are no reason to diverge.

**Comment by gyurco** [comment]
Starting a new repo an d copy/paste everything for every device is rather pointless.

**Comment by Gehstock** [comment]
After this logic you will accepted  Project Files for my Espier Dev Board
in the MiST Main Repo?

Am Fr., 13. Jan. 2023 um 13:07 Uhr schrieb gyurco ***@***.***

**Comment by gyurco** [comment]
Why not? There are some multi-FPGA repos already there.

**Pull request closed without merging**
